# Generated by Django 2.2 on 2022-03-17 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentextra',
            name='date_of_admission',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='studentextra',
            name='date_of_birth',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='studentextra',
            name='father',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='studentextra',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='studentextra',
            name='mother',
            field=models.CharField(blank=True, max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='studentextra',
            name='passport',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/passports/'),
        ),
        migrations.AddField(
            model_name='studentextra',
            name='residence',
            field=models.CharField(choices=[('Dwenem', 'Dwenem'), ('Mpuasu', 'Mpuasu'), ('Adamsu', 'Adamsu'), ('Bodaa', 'Bodaa'), ('Kofitia', 'Kofitia'), ('Adiokor1', 'Adiokor1'), ('Adiokor2', 'Adiokor2'), ('Zezera', 'Zezera'), ('Kwamepim', 'Kwamepim')], max_length=45, null=True),
        ),
        migrations.AddField(
            model_name='teacherextra',
            name='passport',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/passports/'),
        ),
        migrations.AlterField(
            model_name='studentextra',
            name='cl',
            field=models.CharField(choices=[('Nursery', 'Nursery'), ('Preparatory', 'Preparatory'), ('KSA', 'KSA'), ('KSB', 'KSB'), ('KSC', 'KSC')], default='one', max_length=10),
        ),
    ]
