# Generated by Django 2.2 on 2022-03-19 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0009_auto_20220319_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='when_made',
            field=models.DateField(null=True),
        ),
    ]
