# Generated by Django 2.2 on 2022-04-14 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_auto_20220319_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='when_made',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
