# Generated by Django 2.2 on 2022-04-14 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_auto_20220414_1030'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Attendance',
        ),
    ]
