# Generated by Django 2.2 on 2022-04-14 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_delete_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10000, null=True),
        ),
        migrations.AlterField(
            model_name='studentextra',
            name='date_of_admission',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentextra',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentextra',
            name='mobile',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
