# Generated by Django 2.2 on 2022-04-14 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0013_auto_20220414_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='balance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
