# Generated by Django 2.2 on 2022-04-15 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0014_auto_20220414_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='depth',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='balance',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pay',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
