# Generated by Django 2.2 on 2022-04-20 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_auto_20220415_0814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='balance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
