# Generated by Django 2.2 on 2022-04-20 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0016_auto_20220420_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='depth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pay',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
