# Generated by Django 2.2 on 2022-05-22 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0018_auto_20220421_0443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='paid',
        ),
    ]
