# Generated by Django 2.2 on 2022-05-31 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0019_remove_payment_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='when_made',
            field=models.DateField(auto_now=True, null=True),
        ),
    ]
