# Generated by Django 2.2 on 2022-05-31 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0020_auto_20220531_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='when_made',
            field=models.DateField(blank=True, null=True),
        ),
    ]
