# Generated by Django 2.2 on 2022-08-17 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0021_auto_20220531_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentextra',
            name='checkifpaid',
            field=models.BooleanField(default=False),
        ),
    ]
