# Generated by Django 2.2 on 2022-08-29 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0023_studentextra_updatingtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentextra',
            name='fee',
            field=models.FloatField(default=210, null=True),
        ),
    ]
