# Generated by Django 2.2 on 2022-08-29 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0025_studentextra_foodfee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentextra',
            name='foodfee',
            field=models.FloatField(default=2),
        ),
    ]
