# Generated by Django 2.2 on 2022-08-29 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0027_auto_20220829_2022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='pay',
            field=models.FloatField(default=3, null=True),
        ),
    ]
