# Generated by Django 2.2 on 2022-08-29 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0030_auto_20220829_2026'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='pay',
            new_name='foodpay',
        ),
    ]
