# Generated by Django 2.2 on 2022-08-29 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0031_auto_20220829_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='carpay',
            field=models.FloatField(null=True),
        ),
    ]
