# Generated by Django 2.2 on 2022-08-29 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0033_studentextra_carfee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='foodpay',
            new_name='pay',
        ),
    ]
