# Generated by Django 2.2 on 2022-08-30 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0035_auto_20220830_0025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentextra',
            old_name='checkifpaid',
            new_name='checkifpaiddaily',
        ),
    ]
