# Generated by Django 2.2 on 2022-08-30 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0036_auto_20220830_0104'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentextra',
            name='checkifpaidterm',
            field=models.BooleanField(default=False),
        ),
    ]
