# Generated by Django 2.2 on 2022-08-30 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0038_payment_schoolfee'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolFeePayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolfees', models.FloatField(null=True)),
                ('when_made', models.DateField(blank=True, null=True)),
                ('debth', models.FloatField(blank=True, default=210, null=True)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='school.StudentExtra')),
            ],
        ),
    ]
