# Generated by Django 2.2 on 2022-09-05 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0040_remove_payment_schoolfee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentextra',
            name='carfee',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentextra',
            name='foodfee',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
