# Generated by Django 2.2 on 2022-09-11 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0042_auto_20220912_0036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolfeepayment',
            name='debth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='studentextra',
            name='fee',
            field=models.FloatField(default=210, null=True),
        ),
    ]
