# Generated by Django 2.2 on 2022-09-13 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0045_auto_20220914_0035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentextra',
            name='broom',
        ),
        migrations.RemoveField(
            model_name='studentextra',
            name='soap',
        ),
        migrations.RemoveField(
            model_name='studentextra',
            name='troll',
        ),
        migrations.AddField(
            model_name='schoolfeepayment',
            name='broom',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schoolfeepayment',
            name='soap',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schoolfeepayment',
            name='troll',
            field=models.BooleanField(default=False),
        ),
    ]
