# Generated by Django 2.2 on 2022-09-14 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0046_auto_20220914_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='schoolfees',
            field=models.FloatField(null=True),
        ),
    ]
