# Generated by Django 2.2 on 2022-09-18 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0048_studentextra_debt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentextra',
            name='debt',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
