# Generated by Django 2.2 on 2022-09-18 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0049_auto_20220918_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='balance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='depth',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='pay',
            field=models.FloatField(null=True),
        ),
    ]
