# Generated by Django 2.2 on 2022-09-18 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0050_auto_20220918_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentextra',
            name='balance',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
