# Generated by Django 2.2 on 2022-10-05 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0052_auto_20221004_0300'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentextra',
            old_name='do_they_pay',
            new_name='do_they_pay_at_all',
        ),
        migrations.AddField(
            model_name='studentextra',
            name='take_bus',
            field=models.BooleanField(default=False),
        ),
    ]
