# Generated by Django 2.2 on 2022-10-06 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0054_auto_20221005_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentextra',
            name='form_of_payment',
            field=models.CharField(choices=[('Pay_Everything', 'Pay Everything'), ('Dont_Pay', "Don't Pay"), ('Considered', 'Considered')], max_length=40, null=True),
        ),
    ]
