# Generated by Django 2.2 on 2022-10-06 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0055_studentextra_form_of_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentextra',
            name='form_of_transportation',
            field=models.CharField(choices=[('Bus', 'Bus'), ('Walk', 'Walk')], max_length=40, null=True),
        ),
    ]
