# Generated by Django 2.2 on 2022-10-06 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0056_studentextra_form_of_transportation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentextra',
            old_name='form_of_payment',
            new_name='payment_category',
        ),
        migrations.AddField(
            model_name='studentextra',
            name='payment_method',
            field=models.CharField(choices=[('Pay_Per_Term', 'Pay Per Term'), ('Pay_Per_Day', 'Pay Per Day'), ('School_Fees_Aside', 'School Fees Aside')], max_length=40, null=True),
        ),
    ]
