# Generated by Django 2.2 on 2022-10-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0060_auto_20221006_0815'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='pay',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='schoolfees',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
