# Generated by Django 2.2 on 2022-10-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0062_auto_20221008_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='pay',
            field=models.DecimalField(blank=True, decimal_places=14, max_digits=60, null=True),
        ),
    ]
